import type { Metadata } from "next";
import { Lato, Unbounded } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/navbar";
import Footer from "./ui/footer";
import Cta from "./ui/cta";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Moyinol Consulting LTD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${unbounded.variable} antialiased flex flex-col`}
      >
        <NavBar />
        {children}
        <Cta />
        <Footer />
      </body>
    </html>
  );
}
